import { NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getAuthUser, requireRole } from '@/lib/auth';
import { ok, err, unauthorized, forbidden, notFound } from '@/lib/api-response';
import { UserRole, QuoteStatus } from '@prisma/client';

export const dynamic     = 'force-dynamic';
export const maxDuration = 60;

/**
 * POST /api/v1/quotes/:id/publish
 *
 * Fast path: only updates status → SENT and returns public_token.
 * Snapshot generation is triggered separately by the client after receiving the token.
 * Target: < 200ms to return the link.
 */
export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  const t0 = Date.now();
  console.log('[publish] Step 1 - start', t0);

  const user = await getAuthUser(req);
  if (!user) return unauthorized();
  if (!requireRole(user, UserRole.ADMIN, UserRole.SALES, UserRole.MANAGER)) return forbidden();

  const t1 = Date.now();
  console.log('[publish] Step 2 - auth done', t1, `(${t1 - t0}ms)`);

  const quote = await prisma.quote.findUnique({
    where: { id: params.id },
    select: { id: true, quote_type: true, public_token: true, _count: { select: { quote_options: true } } },
  });
  if (!quote) return notFound('Quote');

  // Group quotes use batch pricing — no quote_options required
  if (quote.quote_type === 'PRIVATE' && quote._count.quote_options === 0) {
    return err('Quote must have at least one pricing option before publishing', 400);
  }

  const t2 = Date.now();
  console.log('[publish] Step 3 - quote fetched', t2, `(${t2 - t1}ms)`);

  // Mark SENT — the public_token is already set at quote creation time
  const updatedQuote = await prisma.quote.update({
    where: { id: params.id },
    data:  { status: QuoteStatus.SENT },
    select: { public_token: true },
  });

  const t3 = Date.now();
  console.log('[publish] Step 4 - status updated', t3, `(${t3 - t2}ms) TOTAL so far: ${t3 - t0}ms`);

  // Return the link immediately — snapshot is generated by client in background
  return ok({ public_token: updatedQuote.public_token, snapshot_pending: true });
}
